        ports:
        {{- range seq 0 1000}}
        - name: worlds-port-{{add 25000 .}}
          containerPort: {{add 25000 .}}
          hostIP: placeholder
          hostPort: {{add 25000 .}}
          protocol: UDP
        {{- end -}}

