        {{- range seq 0 10}}
        - name: worlds-{{add 25000 .}}
          containerPort: {{add 25000 .}}
          hostIP: placeholder
          hostPort: {{add 25000 .}}
          protocol: UDP
        {{- end -}}
