apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: "{{ .Chart.Name }}"
  type: {{ .Values.service.type }}
  ports:
  - name: web-port
    port: {{ .Values.env.webPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.webPort | int }}
  - name: admin-port
    port: {{ .Values.env.adminPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.adminPort | int }}
