apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range seq 0 1000}}
  - name: worlds-port-{{add {{ .Values.env.worldsPortRangeStart | int }} }}
    port: {{add {{ .Values.env.worldsPortRangeStart | int }} }}
    protocol: UDP
    targetPort: {{add {{ .Values.env.worldsPortRangeStart | int }} }}
  {{- end -}}
  - name: web-port
    port: {{ .Values.env.webPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.webPort | int }}
  - name: admin-port
    port: {{ .Values.env.adminPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.adminPort | int }}
  selector:
    app: "{{ .Chart.Name }}"

