apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: "{{ .Chart.Name }}"
  type: {{ .Values.service.type }}
  ports:
  - name: worlds-25000
    port: 25000
    protocol: UDP
    targetPort: 25000
  - name: worlds-25001
    port: 25001
    protocol: UDP
    targetPort: 25001
  - name: worlds-25002
    port: 25002
    protocol: UDP
    targetPort: 25002
  - name: worlds-25003
    port: 25003
    protocol: UDP
    targetPort: 25003
  - name: worlds-25004
    port: 25004
    protocol: UDP
    targetPort: 25004
  - name: worlds-25005
    port: 25005
    protocol: UDP
    targetPort: 25005
  - name: worlds-25006
    port: 25006
    protocol: UDP
    targetPort: 25006
  - name: worlds-25007
    port: 25007
    protocol: UDP
    targetPort: 25007
  - name: worlds-25008
    port: 25008
    protocol: UDP
    targetPort: 25008
  - name: worlds-25009
    port: 25009
    protocol: UDP
    targetPort: 25009
  - name: web-port
    port: {{ .Values.env.webPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.webPort | int }}
  - name: admin-port
    port: {{ .Values.env.adminPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.adminPort | int }}

